spring.application.name=wepay-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/wepay
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8085